==============================WARNING: DEPRECATED!==============================
WARNING! This version of bitsandbytes is deprecated. Please switch to `pip install bitsandbytes` and the new repo: https://github.com/TimDettmers/bitsandbytes
==============================WARNING: DEPRECATED!==============================
using device: cuda ['clip.py', '--flagfile=configs/clip/clip_train_behaviour_serengeti_seq.config']
  0%|          | 0/1344 [00:00<?, ?it/s]  0%|          | 1/1344 [00:02<1:00:28,  2.70s/it]  0%|          | 3/1344 [00:02<16:56,  1.32it/s]    0%|          | 5/1344 [00:03<09:06,  2.45it/s]  1%|          | 7/1344 [00:03<05:58,  3.73it/s]  1%|          | 9/1344 [00:03<04:21,  5.11it/s]  1%|          | 11/1344 [00:03<03:26,  6.44it/s]  1%|          | 13/1344 [00:03<02:53,  7.67it/s]  1%|          | 13/1344 [00:03<06:16,  3.54it/s]
Traceback (most recent call last):
  File "/home/luiz/experiments/multimodal-models-in-camera-traps/clip.py", line 127, in <module>
    {"train": train, "test": test}.get(mode)()
  File "/home/luiz/experiments/multimodal-models-in-camera-traps/clip.py", line 77, in train
    for batch in pbar:
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 143, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 143, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 172, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 163, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [450, 1800, 3] at entry 0 and [450, 3600, 3] at entry 1
==============================WARNING: DEPRECATED!==============================
WARNING! This version of bitsandbytes is deprecated. Please switch to `pip install bitsandbytes` and the new repo: https://github.com/TimDettmers/bitsandbytes
==============================WARNING: DEPRECATED!==============================
using device: cuda ['clip.py', '--flagfile=configs/clip/clip_test_behaviour_serengeti_seq_pretrained.config']
evaluation using: /data/luiz/dataset/partitions/behaviour-classifier/serengeti/test.csv
  0%|          | 0/1259 [00:00<?, ?it/s]  0%|          | 1/1259 [00:01<21:08,  1.01s/it]  0%|          | 3/1259 [00:01<06:40,  3.13it/s]  0%|          | 5/1259 [00:01<04:04,  5.13it/s]  0%|          | 6/1259 [00:01<04:55,  4.24it/s]
Traceback (most recent call last):
  File "/home/luiz/experiments/multimodal-models-in-camera-traps/clip.py", line 127, in <module>
    {"train": train, "test": test}.get(mode)()
  File "/home/luiz/experiments/multimodal-models-in-camera-traps/clip.py", line 119, in test
    pred, real, path = evaluation(test_filename)
  File "/home/luiz/experiments/multimodal-models-in-camera-traps/clip.py", line 49, in evaluation
    for batch in pbar:
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 143, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 143, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 172, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 163, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [450, 3600, 3] at entry 0 and [450, 1800, 3] at entry 1
==============================WARNING: DEPRECATED!==============================
WARNING! This version of bitsandbytes is deprecated. Please switch to `pip install bitsandbytes` and the new repo: https://github.com/TimDettmers/bitsandbytes
==============================WARNING: DEPRECATED!==============================
using device: cuda ['clip.py', '--flagfile=configs/clip/clip_test_behaviour_serengeti_seq.config']
evaluation using: /data/luiz/dataset/partitions/behaviour-classifier/serengeti/test.csv
  0%|          | 0/1259 [00:00<?, ?it/s]  0%|          | 1/1259 [00:01<22:49,  1.09s/it]  0%|          | 3/1259 [00:01<07:07,  2.94it/s]  0%|          | 5/1259 [00:01<04:17,  4.88it/s]  0%|          | 6/1259 [00:01<05:12,  4.01it/s]
Traceback (most recent call last):
  File "/home/luiz/experiments/multimodal-models-in-camera-traps/clip.py", line 127, in <module>
    {"train": train, "test": test}.get(mode)()
  File "/home/luiz/experiments/multimodal-models-in-camera-traps/clip.py", line 119, in test
    pred, real, path = evaluation(test_filename)
  File "/home/luiz/experiments/multimodal-models-in-camera-traps/clip.py", line 49, in evaluation
    for batch in pbar:
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 143, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 143, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 172, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 163, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [450, 3600, 3] at entry 0 and [450, 1800, 3] at entry 1
Traceback (most recent call last):
  File "/home/luiz/experiments/multimodal-models-in-camera-traps/blip.py", line 2, in <module>
    import torch
  File "/home/luiz/anaconda3/envs/luiz/lib/python3.9/site-packages/torch/__init__.py", line 218, in <module>
    from torch._C import *  # noqa: F403
RuntimeError: KeyboardInterrupt: <EMPTY MESSAGE>
